### ISSUE TITLE
代码不完整，自建表部分，不存在。

### ISSUE THREAD

**Issue by creazy412** [hongbocui/webChat#1]
github这里的代码，貌似并不跟http://chat.zhbor.com/这里的代码一致吧？？表：webchat_message年月       //（自动生成）用来存储聊天记录
- 表：webchat_broadcast年       //（自动生成）用来存储广播消息
- 表：queue_deamon_status  //（自动生成）用来存储队列状态
- 表： webchat_user		 //（手动建立）用来存储用户数据

储存广播、队列的两张表并没有自动生成。

**Comment by hongbo819** [comment]
并不是代码构架起来就建立的，你说的那两张表，需要将项目用起来才会建立。也就是说  你得说话。。。你得发送广播。。。这样才会看见这两张表

**Comment by creazy412** [comment]
好吧，明白了。
项目对研究wm和GatewayWorker以及websocket还是有用的。
感谢分享。

**Comment by creazy412** [comment]
ps：貌似代码不够完整，流程未通畅。比如chatid 在前端并未传送给event.php，

**Comment by hongbo819** [comment]
event.php里面的第一个方法  onMessage($client_id, $message)     第二个参数$message就是前端发送的json格式数据 。比如 wc_ws.send(JSON.stringify({"type":"say","chatid":chatid,"content":"aaa", "msgType":''}));  怎么会没有chatid呢？

**Comment by creazy412** [comment]
对，你这里说的ws.send没错的。
“ ws.send(JSON.stringify({"type":"say","touser":chatList,"content":input.value}));”这个是从web\index.php下面拷贝过来的代码，是没有chatid属性的。

**Comment by creazy412** [comment]
上面说的是 onSubmit函数的。

**Comment by hongbo819** [comment]
额，我的错，我在readme里面没有说明。web/chat.html是入口文件  可以在nginx里面配置一下
       location / {
                index chat.html;
        }

**Comment by hongbo819** [comment]
index.php已经废弃了

**Comment by creazy412** [comment]
呃。。。好吧，这才和你那博客一样的效果。。。

得去恢复代码了，改动了许多。

**Comment by creazy412** [comment]
我用的apache做的web服务器，
